app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/catboorudb
    username: postgres
    password: alohomora
    pool-size: 30

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false